# Generated by Django 4.2.6 on 2023-11-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_login', models.CharField(max_length=100)),
                ('usuario_password', models.CharField(max_length=100)),
            ],
        ),
    ]
