# Generated by Django 4.2.6 on 2023-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=100)),
                ('ubicacion_ambiente', models.CharField(max_length=100)),
                ('tipo_ambiente', models.CharField(max_length=30)),
                ('capacidad_ambiente', models.PositiveIntegerField()),
            ],
        ),
    ]
