# Generated by Django 4.2.6 on 2023-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_periodo_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_final',
            field=models.DateField(),
        ),
    ]
