# Generated by Django 4.2.6 on 2023-11-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_periodo_duracion_alter_periodo_fecha_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='duracion',
        ),
    ]
