# Generated by Django 4.2.6 on 2023-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_remove_periodo_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=100)),
                ('apellido_docente', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(max_length=10)),
                ('identificacion_docente', models.IntegerField(max_length=10)),
                ('tipo_docente', models.CharField(max_length=100)),
                ('tipoContrato_docente', models.CharField(max_length=100)),
                ('area_docente', models.CharField(max_length=100)),
            ],
        ),
    ]
