# Generated by Django 4.2.6 on 2023-11-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='identificacion_docente',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('horario_dia', models.DateField()),
                ('horario_hora_inicio', models.TimeField()),
                ('horario_hora_fin', models.TimeField()),
                ('horario_duracion', models.DurationField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.ambiente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.docente')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.labor')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.periodo')),
            ],
        ),
    ]
